# Generated by Django 6.0.1 on 2026-01-17 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['application_id'],
            },
        ),
        migrations.CreateModel(
            name='ModelNameAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='engine.aimodel')),
            ],
            options={
                'verbose_name_plural': 'Model Name Aliases',
            },
        ),
        migrations.CreateModel(
            name='UsageAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_model_name', models.CharField(db_index=True, max_length=200)),
                ('analysis_period_start', models.DateTimeField()),
                ('analysis_period_end', models.DateTimeField()),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('successful_requests', models.PositiveIntegerField(default=0)),
                ('max_input_tokens', models.PositiveIntegerField(default=0)),
                ('max_output_tokens', models.PositiveIntegerField(default=0)),
                ('max_total_tokens', models.PositiveIntegerField(db_index=True, default=0)),
                ('avg_input_tokens', models.FloatField(default=0)),
                ('avg_output_tokens', models.FloatField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=10, default=0, max_digits=14)),
                ('avg_cost_per_request', models.DecimalField(db_index=True, decimal_places=10, default=0, max_digits=14)),
                ('avg_latency_sec', models.FloatField(blank=True, null=True)),
                ('tool_usage_percentage', models.FloatField(default=0)),
                ('requires_tools', models.BooleanField(db_index=True, default=False)),
                ('category_distribution', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_analyses', to='engine.application')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_analyses', to='engine.aimodel')),
            ],
            options={
                'verbose_name_plural': 'Usage Analyses',
                'ordering': ['-analysis_period_end'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_model_name', models.CharField(max_length=200)),
                ('recommendation_type', models.CharField(choices=[('cheaper', 'Cost Savings'), ('faster', 'Performance'), ('capable', 'Enhanced Capabilities'), ('balanced', 'Balanced Improvement')], db_index=True, default='cheaper', max_length=20)),
                ('estimated_cost_savings_percent', models.FloatField(default=0)),
                ('estimated_monthly_savings', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('context_window_headroom', models.FloatField(default=0)),
                ('capability_match_score', models.FloatField(default=100)),
                ('reasoning', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='engine.application')),
                ('recommended_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations_for', to='engine.aimodel')),
                ('usage_analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='engine.usageanalysis')),
            ],
            options={
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LLMTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('raw_model_name', models.CharField(db_index=True, max_length=200)),
                ('prompt', models.TextField(blank=True)),
                ('response', models.TextField(blank=True)),
                ('input_token_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('output_token_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_token_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('tool_used', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(db_index=True, default='success', max_length=50)),
                ('category', models.CharField(blank=True, db_index=True, max_length=50)),
                ('estimated_latency_sec', models.FloatField(blank=True, null=True)),
                ('input_cost', models.DecimalField(decimal_places=10, default=0, max_digits=12)),
                ('output_cost', models.DecimalField(decimal_places=10, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(db_index=True, decimal_places=10, default=0, max_digits=12)),
                ('traced_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traces', to='engine.application')),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='engine.aimodel')),
            ],
            options={
                'ordering': ['-traced_at'],
                'indexes': [models.Index(fields=['application', 'raw_model_name'], name='idx_trace_app_model'), models.Index(fields=['application', 'traced_at'], name='idx_trace_app_date'), models.Index(fields=['tool_used', 'application'], name='idx_trace_tool_app'), models.Index(fields=['category', 'application'], name='idx_trace_cat_app')],
            },
        ),
        migrations.AddIndex(
            model_name='usageanalysis',
            index=models.Index(fields=['application', 'analysis_period_end'], name='idx_analysis_app_period'),
        ),
        migrations.AddIndex(
            model_name='usageanalysis',
            index=models.Index(fields=['requires_tools', 'max_total_tokens'], name='idx_analysis_reqs'),
        ),
        migrations.AlterUniqueTogether(
            name='usageanalysis',
            unique_together={('application', 'raw_model_name', 'analysis_period_start')},
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['application', 'is_active', 'confidence_score'], name='idx_rec_app_active_conf'),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['recommendation_type', 'is_active'], name='idx_rec_type_active'),
        ),
    ]
