# Generated by Django 6.0.1 on 2026-01-17 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_application_modelnamealias_usageanalysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_model',
            field=models.ForeignKey(blank=True, help_text='The primary model assigned to this application', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='engine.aimodel'),
        ),
    ]
