# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_add_assigned_model_to_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='categories',
            field=models.JSONField(
                blank=True,
                help_text="List of categories this model is suitable for (e.g., ['coding', 'general', 'finance'])",
                null=True,
            ),
        ),
    ]

