# Generated by Django 6.0.1 on 2026-01-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_add_categories_to_aimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='categories',
            field=models.JSONField(blank=True, db_index=True, help_text="List of categories this model is suitable for (e.g., ['coding', 'general', 'finance'])", null=True),
        ),
    ]
