# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0005_alter_aimodel_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='category',
            field=models.CharField(
                choices=[
                    ('general', 'General Purpose'),
                    ('coding', 'Code Generation & Development'),
                    ('code_review', 'Code Review & Analysis'),
                    ('documentation', 'Technical Documentation'),
                    ('customer_support', 'Customer Support & Helpdesk'),
                    ('chatbot', 'Conversational AI & Chatbots'),
                    ('faq', 'FAQ & Knowledge Base'),
                    ('content_creation', 'Content Writing & Blogging'),
                    ('marketing', 'Marketing Copy & Campaigns'),
                    ('social_media', 'Social Media Content'),
                    ('email', 'Email Composition & Responses'),
                    ('data_analysis', 'Data Analysis & Insights'),
                    ('business_intelligence', 'Business Intelligence'),
                    ('reporting', 'Report Generation'),
                    ('finance', 'Financial Analysis & Trading'),
                    ('accounting', 'Accounting & Bookkeeping'),
                    ('risk_assessment', 'Risk Analysis'),
                    ('healthcare', 'Healthcare & Medical'),
                    ('clinical', 'Clinical Documentation'),
                    ('research', 'Medical Research'),
                    ('legal', 'Legal Research & Analysis'),
                    ('compliance', 'Compliance & Regulatory'),
                    ('contract', 'Contract Analysis'),
                    ('education', 'Education & E-Learning'),
                    ('tutoring', 'Tutoring & Learning Assistant'),
                    ('training', 'Corporate Training'),
                    ('sales', 'Sales & Lead Generation'),
                    ('crm', 'CRM & Customer Management'),
                    ('translation', 'Translation & Localization'),
                    ('multilingual', 'Multilingual Support'),
                    ('search', 'Search & Information Retrieval'),
                    ('rag', 'RAG (Retrieval Augmented Generation)'),
                    ('creative', 'Creative Writing & Storytelling'),
                    ('media', 'Media & Entertainment'),
                    ('moderation', 'Content Moderation'),
                    ('security', 'Security & Threat Detection'),
                    ('ecommerce', 'E-commerce & Product Descriptions'),
                    ('recommendation', 'Product Recommendations'),
                    ('hr', 'Human Resources & Recruiting'),
                    ('recruitment', 'Recruitment & Screening'),
                    ('reasoning', 'Advanced Reasoning & Problem Solving'),
                    ('other', 'Other / Custom Use Case'),
                ],
                db_index=True,
                default='general',
                help_text="Primary category/domain of this application",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['category', 'is_active'], name='idx_app_category_active'),
        ),
    ]

