# Generated by Django migration

from django.db import migrations, models


def migrate_category_to_categories(apps, schema_editor):
    """Migrate single category field to categories list."""
    Application = apps.get_model('engine', 'Application')
    
    for app in Application.objects.all():
        if app.category:
            # Convert single category to list format
            app.categories = [app.category]
        else:
            # Default to general if no category
            app.categories = ['general']
        app.save(update_fields=['categories'])


def reverse_migrate_categories_to_category(apps, schema_editor):
    """Reverse migration: take first category from list."""
    Application = apps.get_model('engine', 'Application')
    
    for app in Application.objects.all():
        if app.categories and len(app.categories) > 0:
            # Take first category from list
            app.category = app.categories[0]
        else:
            # Default to general
            app.category = 'general'
        app.save(update_fields=['category'])


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    from django.db import connection
    with connection.cursor() as cursor:
        # Check if index exists
        if connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_app_category_active';"
            )
            if cursor.fetchone():
                try:
                    cursor.execute("DROP INDEX idx_app_category_active;")
                except Exception:
                    pass  # Index might already be gone
        else:
            # For other databases, use standard SQL
            try:
                cursor.execute("DROP INDEX IF EXISTS idx_app_category_active;")
            except Exception:
                pass  # Index might already be gone


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_add_category_to_application'),
    ]

    operations = [
        # Step 1: Remove old index first (before we remove the field it references)
        migrations.RunPython(
            remove_index_if_exists,
            migrations.RunPython.noop,
        ),
        # Step 2: Add new categories field with db_index from the start
        migrations.AddField(
            model_name='application',
            name='categories',
            field=models.JSONField(
                blank=True,
                db_index=True,
                default=list,
                help_text="List of categories this application belongs to (derived from assigned_model, 1-2 categories)",
            ),
        ),
        # Step 3: Migrate data from category to categories
        migrations.RunPython(
            migrate_category_to_categories,
            reverse_migrate_categories_to_category,
        ),
        # Step 4: Remove old category field
        migrations.RemoveField(
            model_name='application',
            name='category',
        ),
    ]

