# Generated by Django 6.0.1 on 2026-01-18 00:36

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    from django.db import connection
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_app_category_active';"
            )
            if cursor.fetchone():
                try:
                    cursor.execute("DROP INDEX idx_app_category_active;")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0007_change_application_category_to_categories'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='actual_avg_cost_per_request',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='actual_avg_latency_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='actual_success_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='cost_comparison_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='latency_comparison_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='quality_comparison',
            field=models.JSONField(blank=True, default=dict, help_text='Quality comparison scores vs current model'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='quality_overall_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='quality_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Quality scores from LLM-as-judge (correctness, completeness, etc.)'),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='test_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='test_error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='test_samples_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='test_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20),
        ),
    ]
