# Generated by Django 6.0.1 on 2026-01-18 01:22

from django.db import migrations, models


def remove_index_if_exists(apps, schema_editor):
    """Safely remove index if it exists."""
    from django.db import connection
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute(
                "SELECT name FROM sqlite_master WHERE type='index' AND name='idx_app_category_active';"
            )
            if cursor.fetchone():
                try:
                    cursor.execute("DROP INDEX idx_app_category_active;")
                except Exception:
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0008_remove_application_idx_app_category_active_and_more'),
    ]

    operations = [
        migrations.RunPython(
            remove_index_if_exists,
            migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name='aimodel',
            name='is_deprecated',
            field=models.BooleanField(db_index=True, default=False, help_text='Model has been deprecated by the provider and is no longer available'),
        ),
    ]
