# Generated by Django 6.0.1 on 2026-01-17 17:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('default_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('model_type', models.CharField(choices=[('chat', 'Chat'), ('text', 'Text Completion'), ('embedding', 'Embedding'), ('audio', 'Audio'), ('image', 'Image Generation'), ('moderation', 'Moderation')], db_index=True, default='chat', max_length=20)),
                ('context_window', models.PositiveIntegerField(blank=True, db_index=True, help_text='Maximum output tokens (max_tokens parameter)', null=True)),
                ('max_completion_tokens', models.PositiveIntegerField(blank=True, db_index=True, help_text='Maximum completion tokens (for reasoning models)', null=True)),
                ('supports_image_input', models.BooleanField(db_index=True, default=False)),
                ('supports_tools', models.BooleanField(db_index=True, default=False)),
                ('supports_audio', models.BooleanField(db_index=True, default=False)),
                ('supports_pdf', models.BooleanField(db_index=True, default=False)),
                ('supports_doc', models.BooleanField(db_index=True, default=False)),
                ('has_reasoning', models.BooleanField(db_index=True, default=False)),
                ('supports_cache_control', models.BooleanField(db_index=True, default=False)),
                ('additional_capabilities', models.JSONField(blank=True, default=dict)),
                ('parameter_config', models.JSONField(blank=True, default=dict)),
                ('thinking_budget_min', models.PositiveIntegerField(blank=True, null=True)),
                ('thinking_budget_max', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.provider')),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pricing', serialize=False, to='core.aimodel')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('request_token_price', models.DecimalField(db_index=True, decimal_places=8, default=0, help_text='Price per 1M input tokens', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('response_token_price', models.DecimalField(db_index=True, decimal_places=8, default=0, help_text='Price per 1M output tokens', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_write_input_token_price', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('cache_read_input_token_price', models.DecimalField(decimal_places=8, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('request_audio_token_price', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('response_audio_token_price', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image_pricing', models.JSONField(blank=True, default=dict)),
                ('additional_units', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing',
                'indexes': [models.Index(fields=['request_token_price'], name='idx_request_price'), models.Index(fields=['response_token_price'], name='idx_response_price'), models.Index(fields=['request_token_price', 'response_token_price'], name='idx_token_prices')],
            },
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['model_type', 'is_active'], name='idx_model_type_active'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['context_window', 'is_active'], name='idx_context_active'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['has_reasoning', 'is_active'], name='idx_reasoning_active'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['provider', 'model_type'], name='idx_provider_type'),
        ),
        migrations.AddIndex(
            model_name='aimodel',
            index=models.Index(fields=['supports_image_input', 'supports_tools', 'has_reasoning'], name='idx_capabilities'),
        ),
        migrations.AlterUniqueTogether(
            name='aimodel',
            unique_together={('provider', 'name')},
        ),
    ]
